### ISSUE TITLE
Registered services in user place is not an array

### ISSUE THREAD

**Issue by goodhumored** [MoeidHeidari/ComfortechOpenApi#6]
![image](https://user-images.githubusercontent.com/101120473/194587200-040d1af8-266b-4dfd-a779-ebb3c1a72a93.png)
Registered services **should** be an array of services, not one single service

**Comment by BurnedScarecrow** [comment]
![image](https://user-images.githubusercontent.com/57987421/194825490-74fa921b-2e55-4704-99b1-458590bb7f45.png)
Fixed it to array
